import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ParticlesCanvas from "@/components/particles/partcilesScence";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ParticlesCanvas/>
        {children}
        <div className="fixed bottom-0 left-0 right-0 text-gray-400 text-xs tracking-wide mx-auto text-center">
          NepaliGPT v2
        </div>
      </body>
    </html>
  );
}
